// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.5
// source: api/proto/solenix.proto

package solenixpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_api_proto_solenix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{0}
}

func (x *DataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points        []*DataPoint           `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_api_proto_solenix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{1}
}

func (x *Series) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Series) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Series) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_api_proto_solenix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{2}
}

func (x *PushRequest) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       int32                  `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"` // количество записанных серий
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_api_proto_solenix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{3}
}

func (x *PushResponse) GetWritten() int32 {
	if x != nil {
		return x.Written
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	From          int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`    // Unix nanoseconds, 0 = без ограничения
	To            int64                  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`        // Unix nanoseconds, 0 = без ограничения
	Window        string                 `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"` // опционально: "1m", "5m", "1h" — включает агрегацию
	Agg           string                 `protobuf:"bytes,6,opt,name=agg,proto3" json:"agg,omitempty"`       // опционально: "avg", "min", "max", "sum", "count"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_solenix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *QueryRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *QueryRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *QueryRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *QueryRequest) GetAgg() string {
	if x != nil {
		return x.Agg
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_solenix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_solenix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SubscribeRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_solenix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_solenix_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_api_proto_solenix_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{9}
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []string               `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_proto_solenix_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_solenix_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_solenix_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsResponse) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_api_proto_solenix_proto protoreflect.FileDescriptor

const file_api_proto_solenix_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/solenix.proto\x12\asolenix\"?\n" +
	"\tDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xbc\x01\n" +
	"\x06Series\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x123\n" +
	"\x06labels\x18\x02 \x03(\v2\x1b.solenix.Series.LabelsEntryR\x06labels\x12*\n" +
	"\x06points\x18\x03 \x03(\v2\x12.solenix.DataPointR\x06points\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\vPushRequest\x12'\n" +
	"\x06series\x18\x01 \x03(\v2\x0f.solenix.SeriesR\x06series\"(\n" +
	"\fPushResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\x05R\awritten\"\xea\x01\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x129\n" +
	"\x06labels\x18\x02 \x03(\v2!.solenix.QueryRequest.LabelsEntryR\x06labels\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\x12\x16\n" +
	"\x06window\x18\x05 \x01(\tR\x06window\x12\x10\n" +
	"\x03agg\x18\x06 \x01(\tR\x03agg\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\rQueryResponse\x12'\n" +
	"\x06series\x18\x01 \x03(\v2\x0f.solenix.SeriesR\x06series\"\xa4\x01\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12=\n" +
	"\x06labels\x18\x02 \x03(\v2%.solenix.SubscribeRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x10\n" +
	"\x0eMetricsRequest\"+\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\ametrics\x18\x01 \x03(\tR\ametrics2\xaf\x02\n" +
	"\tSolenixDB\x123\n" +
	"\x04Push\x12\x14.solenix.PushRequest\x1a\x15.solenix.PushResponse\x126\n" +
	"\x05Query\x12\x15.solenix.QueryRequest\x1a\x16.solenix.QueryResponse\x12<\n" +
	"\tSubscribe\x12\x19.solenix.SubscribeRequest\x1a\x12.solenix.DataPoint0\x01\x129\n" +
	"\x06Health\x12\x16.solenix.HealthRequest\x1a\x17.solenix.HealthResponse\x12<\n" +
	"\aMetrics\x12\x17.solenix.MetricsRequest\x1a\x18.solenix.MetricsResponseB7Z5github.com/synthetis-tech/solenix/api/proto;solenixpbb\x06proto3"

var (
	file_api_proto_solenix_proto_rawDescOnce sync.Once
	file_api_proto_solenix_proto_rawDescData []byte
)

func file_api_proto_solenix_proto_rawDescGZIP() []byte {
	file_api_proto_solenix_proto_rawDescOnce.Do(func() {
		file_api_proto_solenix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_solenix_proto_rawDesc), len(file_api_proto_solenix_proto_rawDesc)))
	})
	return file_api_proto_solenix_proto_rawDescData
}

var file_api_proto_solenix_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_solenix_proto_goTypes = []any{
	(*DataPoint)(nil),        // 0: solenix.DataPoint
	(*Series)(nil),           // 1: solenix.Series
	(*PushRequest)(nil),      // 2: solenix.PushRequest
	(*PushResponse)(nil),     // 3: solenix.PushResponse
	(*QueryRequest)(nil),     // 4: solenix.QueryRequest
	(*QueryResponse)(nil),    // 5: solenix.QueryResponse
	(*SubscribeRequest)(nil), // 6: solenix.SubscribeRequest
	(*HealthRequest)(nil),    // 7: solenix.HealthRequest
	(*HealthResponse)(nil),   // 8: solenix.HealthResponse
	(*MetricsRequest)(nil),   // 9: solenix.MetricsRequest
	(*MetricsResponse)(nil),  // 10: solenix.MetricsResponse
	nil,                      // 11: solenix.Series.LabelsEntry
	nil,                      // 12: solenix.QueryRequest.LabelsEntry
	nil,                      // 13: solenix.SubscribeRequest.LabelsEntry
}
var file_api_proto_solenix_proto_depIdxs = []int32{
	11, // 0: solenix.Series.labels:type_name -> solenix.Series.LabelsEntry
	0,  // 1: solenix.Series.points:type_name -> solenix.DataPoint
	1,  // 2: solenix.PushRequest.series:type_name -> solenix.Series
	12, // 3: solenix.QueryRequest.labels:type_name -> solenix.QueryRequest.LabelsEntry
	1,  // 4: solenix.QueryResponse.series:type_name -> solenix.Series
	13, // 5: solenix.SubscribeRequest.labels:type_name -> solenix.SubscribeRequest.LabelsEntry
	2,  // 6: solenix.SolenixDB.Push:input_type -> solenix.PushRequest
	4,  // 7: solenix.SolenixDB.Query:input_type -> solenix.QueryRequest
	6,  // 8: solenix.SolenixDB.Subscribe:input_type -> solenix.SubscribeRequest
	7,  // 9: solenix.SolenixDB.Health:input_type -> solenix.HealthRequest
	9,  // 10: solenix.SolenixDB.Metrics:input_type -> solenix.MetricsRequest
	3,  // 11: solenix.SolenixDB.Push:output_type -> solenix.PushResponse
	5,  // 12: solenix.SolenixDB.Query:output_type -> solenix.QueryResponse
	0,  // 13: solenix.SolenixDB.Subscribe:output_type -> solenix.DataPoint
	8,  // 14: solenix.SolenixDB.Health:output_type -> solenix.HealthResponse
	10, // 15: solenix.SolenixDB.Metrics:output_type -> solenix.MetricsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_solenix_proto_init() }
func file_api_proto_solenix_proto_init() {
	if File_api_proto_solenix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_solenix_proto_rawDesc), len(file_api_proto_solenix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_solenix_proto_goTypes,
		DependencyIndexes: file_api_proto_solenix_proto_depIdxs,
		MessageInfos:      file_api_proto_solenix_proto_msgTypes,
	}.Build()
	File_api_proto_solenix_proto = out.File
	file_api_proto_solenix_proto_goTypes = nil
	file_api_proto_solenix_proto_depIdxs = nil
}
